name: Deploy to VPS Restoreplus (CLIENT)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            source ~/.nvm/nvm.sh
            nvm use 18
            cd /var/www/restoreplus-client
            git pull origin main
            pnpm install --frozen-lockfile
            pnpm build
            pm2 restart restoreplus-client
